import type { Metadata } from "next";
import { Inter } from "next/font/google";
import './theme-config.css';
import "./globals.css";
import { Theme, ThemePanel } from "@radix-ui/themes";
import NavbarTab from "./navbar";
import '@radix-ui/themes/styles.css';

const inter = Inter({ 
  subsets: ["latin"],
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <Theme accentColor="teal" grayColor="sand" panelBackground="solid" radius="large">
          <NavbarTab />
          <main className="p-5">{children}</main>
        </Theme>
      </body>
    </html>
  );
}
